
-- Seed default content for all sections
INSERT INTO public.site_content (section_key, content) VALUES
('hero', '{"title":"Creative Productivity","subtitle":"Nexus CPN","description":"Building powerful digital tools and solutions for everyone. We craft bots, web apps, and services that simplify your digital life.","badge":"◆ Welcome ◆","cta_text":"Explore Tools","version":"v2.0.25"}'::jsonb),
('stats', '{"title":"CAT-CPN-GO","subtitle":"Real-time statistics from our main repository","github_url":"https://github.com/Ph462/cpn-creative-hub","items":[{"label":"Stars","value":"418"},{"label":"Forks","value":"1,551"},{"label":"Watchers","value":"418"},{"label":"Issues","value":"44"}]}'::jsonb),
('projects', '{"title":"What We Create","subtitle":"Check out everything we have made!","items":[{"title":"CPN Bot","description":"A multi-purpose Discord bot with moderation, music, and fun commands.","status":"Active","category":"Bots","image":"https://images.unsplash.com/photo-1677442136019-21780ecad995?w=600&q=80","link":"#"},{"title":"Auto-Mod Bot","description":"Automated moderation bot for Telegram groups with spam detection.","status":"Active","category":"Bots","image":"https://images.unsplash.com/photo-1531746790095-e5e1408e10f8?w=600&q=80","link":"#"},{"title":"WhatsApp Helper","description":"Customer support automation bot for WhatsApp Business.","status":"Active","category":"Bots","image":"https://images.unsplash.com/photo-1611746872915-64382b5c76da?w=600&q=80","link":"#"},{"title":"Portfolio Builder","description":"Generate stunning developer portfolios in minutes.","status":"Active","category":"Web Tools","image":"https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=600&q=80","link":"#"},{"title":"Link Shortener","description":"Custom branded short URLs with analytics tracking.","status":"Active","category":"Web Tools","image":"https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600&q=80","link":"#"},{"title":"SEO Analyzer","description":"Full website SEO audit with actionable improvement tips.","status":"Active","category":"Web Tools","image":"https://images.unsplash.com/photo-1432888498266-38ffec3eaf0a?w=600&q=80","link":"#"},{"title":"Cloud Hosting","description":"Affordable cloud hosting for small to medium projects.","status":"Active","category":"Services","image":"https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=600&q=80","link":"#"},{"title":"API Gateway","description":"Managed API gateway with rate limiting and monitoring.","status":"Active","category":"Services","image":"https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=600&q=80","link":"#"},{"title":"CPN Mobile","description":"All-in-one mobile companion app for CPN tools on the go.","status":"Beta","category":"Apps","image":"https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=600&q=80","link":"#"},{"title":"Task Tracker","description":"Lightweight task management app with team collaboration.","status":"Active","category":"Apps","image":"https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?w=600&q=80","link":"#"}]}'::jsonb),
('testimonials', '{"title":"What People Say","subtitle":"Feedback from our community and users","items":[{"text":"CPN Bot completely transformed how we manage our Discord server. The moderation tools are incredible!","author":"Alex M.","date":"Feb 2026"},{"text":"The portfolio builder saved me hours. I had a professional site up in under 10 minutes.","author":"Sarah K.","date":"Jan 2026"},{"text":"Amazing support team. They helped me set up the API gateway for my startup in no time.","author":"James O.","date":"Mar 2026"},{"text":"The link shortener with analytics is a game changer for our marketing campaigns.","author":"Priya R.","date":"Feb 2026"},{"text":"I love the auto-mod bot. Our Telegram group has been spam-free since we set it up.","author":"David L.","date":"Jan 2026"},{"text":"CPN Mobile is sleek and fast. Having all tools in one app on my phone is so convenient.","author":"Fatima N.","date":"Mar 2026"}]}'::jsonb),
('founder', '{"name":"Oundo Nelson","role":"Founder & Lead Developer","bio":"Passionate about creating innovative digital solutions that make a difference. With over 4 years of experience in full-stack development, I build tools that empower communities and simplify workflows across Africa and beyond.","location":"Uganda, East Africa","tagline":"Creator & Problem Solver","skills":[{"name":"Full-Stack Development","percent":92},{"name":"Bot Development","percent":88},{"name":"UI/UX Design","percent":85},{"name":"Cloud Infrastructure","percent":78},{"name":"Mobile Development","percent":75}]}'::jsonb),
('connect', '{"title":"Connect With Us","subtitle":"Follow us on social media for updates, tutorials, and new releases","whatsapp_channel":"https://whatsapp.com/channel/catcpn","socials":[{"label":"YouTube","href":"https://youtube.com/@catcpn"},{"label":"Instagram","href":"https://instagram.com/catcpn"},{"label":"WhatsApp","href":"https://wa.me/catcpn"}]}'::jsonb)
ON CONFLICT (section_key) DO UPDATE SET content = EXCLUDED.content, updated_at = now();
